### ISSUE TITLE
I'm not sure the example works?

### ISSUE THREAD

**Issue by donalm** [Abestanis/TwistedOAuth2#1]
Apologies if this should be obvious - I'm new to OAuth2 and just trying to understand the concepts.

Should I expect the example to work in its current state, or do I need to modify it in some way before I try to use it? I haven't managed to work out how it ought to function.

At /oauth2 I get a 400 response:
`{"error": "invalid_request", "error_description": "Request was missing the 'client_id' parameter"}`

At /clock I get a 401 response:
`{"scope": "VIEW_CLOCK", "error_description": "No access token provided", "error": "invalid_request"}`

The second response does have a www-authenticate header:
`WWW-Authenticate: Bearer realm="http://localhost:8880/clock"`

I'd appreciate any help to get this sample running.

Thanks

DJM

**Comment by Abestanis** [comment]
First of all, thank you for your feedback, it is very much appreciated!

The example is working correctly and the responses you get are as expected.
It implements the ```Authorization Code Grant``` flow, the most complex of them all, so it can be confusing at first.

I will do my best to explain the concept:

The ```Authorization Code Grant``` flow requires two software components: The server and the [client](https://github.com/Abestanis/TxOauth2/blob/master/README.md#terminology).
This project allows you to implement the server component.
As the server, we have resources that are owned by a user (in the example, that would be the ```http://localhost:8880/clock``` page). The server only grants access to the resource to clients who provide a valid access token.

To obtain such a token, the client has to use the authorization and the token endpoint.
In the example, the authorization endpoint is available at ```http://localhost:8880/oauth2```
and the token endpoint is available at ```http://localhost:8880/oauth2/token```.

The ```Authorization Code Grant``` flow is split up in two parts:

1. The client has to redirect the user to the authorization endpoint with a GET request.
   There, the user should be able to choose if he/she wants to give the client access to the resource.
   When redirecting the user to the authorization endpoint, the client needs to pass along some parameters with the request.
   This is why your got the ```invalid_request``` response, you did not pass any parameters with your request.
   The required parameters are:
   * client_id: An id that identifies the client. The client must be known to the server, you need to register it as demonstrated [in the example](https://github.com/Abestanis/TxOauth2/blob/master/example/main.py#L121).
   * redirect_uri: An url to redirect the user to after he/she chooses to allow or deny access to the resource. This url also needs to be registered with the client. (Optional if the client has only one return uri registered)
   * response_type: This indicates the type of authentication the client wants to receive. For the ```Authorization Code Grant``` flow this must always be ```code```.
   * state: This parameter has no meaning to the server, but it is required to put its exact contents as a parameter into the response when redirecting the user to the ```redirect_uri```. (Optional)
   * scope: The scope indicates which resources the client requests access to. If the client wants access to multiple scopes, it should send them as a space separated string.
     The names of scopes that the server knows is entirely up to you to decide when you implement the server. [The example supports two](https://github.com/Abestanis/TxOauth2/blob/master/example/main.py#L78): ```All``` and ```VIEW_CLOCK```. (Optional if a default scope was configured)
   
   The client must pass these parameters as url-parameters. A possible request for the example would be
   ```http request
   GET http://localhost:8880/oauth2?client_id=test&response_type=code&scope=VIEW_CLOCK&state=xyz&redirect_uri=https://clientServer.com/return
   ```
   If the user denies the request, the server redirects the user to the ```redirect_uri```, in the example:
   ```http request
   GET https://clientserver.com/return?error=access_denied&error_description=The+resource+owner+denied+the+request&state=xyz
   ``` 
   
   If the user approves the request, the server redirects the user to the ```redirect_uri```, in the example:
   ```http request
   GET https://clientserver.com/return?state=xyz&code=89bb1b6f-0eee-4725-baff-f1fa0677f10f
   ```
   The code (```89bb1b6f-0eee-4725-baff-f1fa0677f10f```) returned to the client is **not** a valid access token yet.
   It is a short living code that the client can use to acquire an access token at the token endpoint in part 2.

2. The client makes a POST request to the token endpoint to get an access token and a refresh token in exchange for the code from part 1.
   The refresh token is a long living token that can be used to get new access tokens from the token endpoint directly.
   The request must have a ```application/x-www-form-urlencoded``` content type.
   It must include the following parameters:
   * grant_type: Indicates the type of request, for the ```Authorization Code Grant``` flow this must be ```authorization_code```.
   * client_id: An id that identifies the client. Must be the same as the one used in part 1.
   * client_secret: The secret (password) of the client. There are other options for authenticating the client.
   * code: The code obtained from part 1.
   * redirect_uri: The redirect uri that was used in part 1.
   
   A possible request for the example would be
   ```http request
   POST http://localhost:8880/oauth2/token?grant_type=authorization_code&client_id=test&client_secret=test_secret&code=89bb1b6f-0eee-4725-baff-f1fa0677f10f&redirect_uri=https://clientServer.com/return
   Content-Type: application/x-www-form-urlencoded
   ```
   
   You can test the request with python (after installing the ```requests``` package)
   ```python
   import requests
   code = '89bb1b6f-0eee-4725-baff-f1fa0677f10f'
   print(requests.post('http://localhost:8880/oauth2/token?grant_type=authorization_code&client_id=test&client_secret=test_secret&redirect_uri=https://clientServer.com/return&code=' + code, headers={'content-type': 'application/x-www-form-urlencoded'}).text)
   ```
   
   If the request was invalid, the server returns an error. For example, if the code was invalid
   ```json
   {"error": "invalid_grant", "error_description": "The provided authorization code is invalid"}
   ``` 
   
   If the request was valid, you will receive a response with a new access token and refresh token, e.g.
   ```json
   {"access_token": "275aa21a-a3ab-4a0b-8fbc-caeebcbd940d", "token_type": "Bearer", "scope": "All", "expires_in": 3600, "refresh_token": "405d2baa-f2ce-4f97-8ddd-2d59ac950c84"}
   ```
   
   The client can now use the access token to access the resource that is owned by the user.
   The access token can either be transmitted in the ```Authorization``` header with the ```Bearer ``` prefix 
   ```http request
   GET http://localhost:8880/clock
   Authorization: Bearer 275aa21a-a3ab-4a0b-8fbc-caeebcbd940d
   ```
   
   or as an url parameter:
   ```http request
   GET http://localhost:8880/clock?access_token=275aa21a-a3ab-4a0b-8fbc-caeebcbd940d
   ```

I can recommend this website, if you want another description of the different oauth2 flows:
https://www.oauth.com/oauth2-servers/server-side-apps/example-flow/
 
 Hopefully this is helpful to you. Feel free to ask if you have any other questions or close the issue if I could answer your question.

**Comment by donalm** [comment]
Thanks so much for that detailed reply - with your help I managed to get it working.
